server:
  applicationConnectors:
    - type: http
      port: 8080  # API Gateway HTTP Port
  adminConnectors:
    - type: http
      port: 8081  # Admin Port

logging:
  level: INFO
  appenders:
    - type: console
      timeZone: UTC
    - type: file
      currentLogFilename: logs/api-gateway.log
      archivedLogFilenamePattern: logs/api-gateway-%d.log.gz
      archivedFileCount: 5
      timeZone: UTC
      threshold: INFO

databaseUrl: jdbc:postgresql://postgres:5432/political_data
databaseUser: "postgres"
databasePassword: "postgres"
databaseDriverClass: org.postgresql.Driver
databaseMaxConnections: 10

kafkaBootstrapServers: "localhost:9092"

elasticsearchHost: "http://localhost:9200"

minioEndpoint: "http://localhost:9000"
minioAccessKey: "minioadmin"
minioSecretKey: "minioadmin"
minioBucket: "political-media"